name: build-nushell-images
on:
  push:
    branches:
      - main
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # build once a week on sunday at 00:00

jobs:
  build-individual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hustcer/setup-nu@v3.13
        with:
          version: v0.96.1

      - uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v3.6.0

      - name: Run build and push script
        run: nu ./build.nu
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_PR_NUMBER: ${{ github.event.number }}
          GH_BRANCH: ${{ github.ref_name }}
